""" vapory/__init__.py """

from vapory.version import __version__
from vapory.vapory import (
    Background, BicubicPatch, Blob, Bokeh, BoundedBy, Box, BumpMap,
    Camera, ClippedBy, ColorMap, ColourMap, Cone, ContainedBy, Cubic,
    Cylinder, Density, DensityMap, Difference, Disc, FaceIndices,
    Finish, Fog, HeightField, ImageMap, ImagePattern, Interior,
    InteriorTexture, Intersection, Irid, Isosurface, JuliaFractal,
    Lathe, LightGroup, LightSource, LooksLike, Macro, Material,
    MaterialMap, Media, Merge, Mesh, Mesh2, Normal, NormalIndices,
    NormalMap, NormalVectors, Object, Ovus, POVRayElement, POVRayMap,
    Parametric, Photons, Pigment, PigmentMap, PigmentPattern, Plane,
    Poly, Polygon, Polynomial, Prism, ProjectedThrough, Quadric,
    Quartic, Radiosity, Rainbow, Reflection, Scattering, Scene,
    SkySphere, Slope, SlopeMap, SmoothTriangle, Sor, Sphere,
    SphereSweep, Spline, Subsurface, Superellipsoid, Text, Texture,
    TextureList, TextureMap, Torus, Triangle, Union, UvIndices,
    VertexVectors, Warp,
)

__all__ = [
    "__version__",
    # All classes from vapory.py
    "Scene",
    "POVRayElement",
    "POVRayMap",
    "Macro",
    "Spline",
    "Camera",
    "Bokeh",
    "Background",
    "Fog",
    "SkySphere",
    "Rainbow",
    "LightSource",
    "LooksLike",
    "ProjectedThrough",
    "LightGroup",
    "Radiosity",
    "Photons",
    "Object",
    "Blob",
    "Parametric",
    "Prism",
    "Sphere",
    "SphereSweep",
    "Superellipsoid",
    "Sor",
    "Text",
    "Torus",
    "Box",
    "Cone",
    "Cylinder",
    "HeightField",
    "Isosurface",
    "ContainedBy",
    "JuliaFractal",
    "Lathe",
    "Ovus",
    "BicubicPatch",
    "Disc",
    "Mesh",
    "Mesh2",
    "FaceIndices",
    "NormalIndices",
    "NormalVectors",
    "UvIndices",
    "VertexVectors",
    "Polygon",
    "Triangle",
    "SmoothTriangle",
    "Plane",
    "Poly",
    "Cubic",
    "Quartic",
    "Polynomial",
    "Quadric",
    "Union",
    "Intersection",
    "Difference",
    "Merge",
    "ClippedBy",
    "BoundedBy",
    "Material",
    "Texture",
    "Pigment",
    "ColorMap",
    "ColourMap",
    "PigmentMap",
    "Normal",
    "NormalMap",
    "SlopeMap",
    "BumpMap",
    "Finish",
    "Subsurface",
    "Reflection",
    "Irid",
    "TextureList",
    "TextureMap",
    "MaterialMap",
    "InteriorTexture",
    "PigmentPattern",
    "Slope",
    "ImagePattern",
    "Warp",
    "ImageMap",
    "Media",
    "Interior",
    "Scattering",
    "Density",
    "DensityMap",
]